name: productivity-dashboard

services:
- name: web
  github:
    repo: mudit-mohit/AI-Powered-Worker-Productivity-Dashboard
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.heroku
  envs:
  - key: FLASK_ENV
    value: production
  - key: REACT_APP_API_URL
    value: ""
  http_port: 5000

static_sites:
- source_dir: frontend/build
  routes:
  - path: /
